name: BugOps
on: issue_comment # this is used for PRs https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_review


permissions:
  contents: read
  issues: write
  pull-requests: write

env:
  MAGIC_COMMENT: "/bug" # this is a parameter you can change

jobs:
  see-comment:
    # this filters for only comments made on a pull request
    if: (github.event.issue.pull_request != null)
    runs-on: ubuntu-latest
    steps:
    - name: see payload # this step is for debugging purposes only, so you can see the payload. 
      run: echo "PAYLOAD:\n${PAYLOAD}\n"
      env:
        PAYLOAD: ${{ toJSON(github.event) }}
        
    - name: filter for magic comment
      id: filter
      if: contains(github.event.comment.body, env.MAGIC_COMMENT)
      run: echo "magic comment detected"
  
    - name: Make a comment with the GitHub API
      uses: actions/github-script@v6
      if: steps.get-magic-value.outcome == 'success' 
      with:
        script: |
           var msg = `bug`
           github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg
            })
    
