name: ghapi
on: pull_request

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  ghapi:
    runs-on: ubuntu-latest
    steps:        
    - name: install dependencies
      run: pip install ghapi 

    - name: see payload # this step is for debugging purposes only, so you can see the payload. 
      run: |
        echo "PAYLOAD:\n${PAYLOAD}\n"
        echo ${{ github.run_id }}
      env:
        PAYLOAD: ${{ toJSON(github.event) }}
      
    - name: Make a comment with the GitHub API
      uses: actions/github-script@v6
      with:
        script: |
           var msg = `👋 Hello!  You commented on this PR with GitHub Script`
           github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg
            })
