on: push


jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
    - name: using shell command to display secret 
    - run: echo $MY_VAR1
      env:
        MY_VAR1: ${{ secrets.MY_SECRET }}
    
    - name: using python command to display secret 
    - run : |
        import os
        print(len(os.getenv('MY_VAR')))
        print(os.getenv('MY_VAR'))
      shell: python
      env:
        MY_VAR: ${{ secrets.MY_SECRET }}
